<?php /* @var $this ECA_Message_Block_Form */?>

<?php /* ?>
<?php echo $this->getHelloWorld(); ?>
<?php echo $this->__('Current time is %s', $this->formatTime()); ?>
<?php */ ?>

form POST, action eca_message/index/save + saveAction dans le controller
input text, id=title, name=title
textarea, id=content, name=content
button submit

+ javascript de vérification des champs : title et content obligatoires
